### PR TITLE
Retrieve the image path also on iOS

### PR DESCRIPTION
**Pull request by ataylor32**

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Thanks for the contribution but I noticed that ALAssetsLibrary [is deprecated in iOS 9.0+](https://developer.apple.com/documentation/assetslibrary/alassetslibrary).

Could you please change it to [PHPhotoLibrary](https://developer.apple.com/documentation/photokit/phphotolibrary)?  (iOS 8+)
[This link should help](https://stackoverflow.com/a/53627022)

**Comment by ataylor32** [comment]
@rodrigograca31 Yeah, I knew it was deprecated at the time that I made the pull request. I had actually already tried implementing `PHPhotoLibrary` myself, but I don't know iOS development, so I got lost pretty quickly when attempting. But I still think this pull request would be worth merging because it makes iOS behave the same as Android (currently they behave differently). I actually need this feature for a project I'm working on. It's a step in the right direction, and maybe somebody who knows iOS development can implement `PHPhotoLibrary`

**Comment by rodrigograca31** [comment]
Ok, yeah you got a good point.

Can you just answer something? 
Its deprecated in iOS 9, but we are in iOS 13, it can still be used right?
(because its deprecated but not removed)

**Comment by ataylor32** [comment]
@rodrigograca31 I tried it on iOS 13.2.3 today and it worked.

**Comment by rodrigograca31** [comment]
Thanks for the contribution @ataylor32 ! :heart:

**Pull request merged**
